add_executable(kcf_action_app_server src/server_main.cpp)
set_target_properties(kcf_action_app_server PROPERTIES OUTPUT_NAME kcf_action_server)
add_executable(kcf_action_app_client src/client_main.cpp)
set_target_properties(kcf_action_app_client PROPERTIES OUTPUT_NAME kcf_action_client)
add_executable(kcf_action_app_bringup src/bringup_main.cpp ../../bringup/src/bringup.cpp)
target_include_directories(kcf_action_app_bringup PRIVATE ../../bringup/include)
foreach(target kcf_action_app_server kcf_action_app_client kcf_action_app_bringup)
    target_include_directories(${target} PRIVATE include)
    target_link_libraries(${target} PRIVATE kcf_core)
endforeach()
add_dependencies(kcf_action_app_bringup kcf_action_app_server kcf_action_app_client)
